/**
 * Login autostart (#648, plan §3): user-level, admin-free, opt-in only
 * (`miqro-context install --autostart`).
 *
 *   Windows  %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\miqro-context.cmd
 *   macOS    ~/Library/LaunchAgents/com.miqro.context.plist
 *   Linux    ~/.config/systemd/user/miqro-context.service
 *
 * Generators are pure (content is unit-tested); the target directory honours
 * MIQRO_CONTEXT_AUTOSTART_DIR so tests never touch the real startup folders.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export type AutostartPaths = {
  /** Directory the entry lives in. */
  dir: string;
  /** File name inside the directory. */
  fileName: string;
  filePath: string;
};

export function autostartPaths(platform: NodeJS.Platform, env: NodeJS.ProcessEnv = process.env): AutostartPaths {
  const override = env["MIQRO_CONTEXT_AUTOSTART_DIR"];
  if (override) {
    return { dir: override, fileName: fileNameFor(platform), filePath: path.join(override, fileNameFor(platform)) };
  }
  const home = os.homedir();
  switch (platform) {
    case "win32": {
      const appData = env["APPDATA"] ?? path.join(home, "AppData", "Roaming");
      const dir = path.join(appData, "Microsoft", "Windows", "Start Menu", "Programs", "Startup");
      return { dir, fileName: fileNameFor(platform), filePath: path.join(dir, fileNameFor(platform)) };
    }
    case "darwin": {
      const dir = path.join(home, "Library", "LaunchAgents");
      return { dir, fileName: fileNameFor(platform), filePath: path.join(dir, fileNameFor(platform)) };
    }
    default: {
      const dir = path.join(home, ".config", "systemd", "user");
      return { dir, fileName: fileNameFor(platform), filePath: path.join(dir, fileNameFor(platform)) };
    }
  }
}

export function fileNameFor(platform: NodeJS.Platform): string {
  switch (platform) {
    case "win32":
      return "miqro-context.cmd";
    case "darwin":
      return "com.miqro.context.plist";
    default:
      return "miqro-context.service";
  }
}

export type AutostartEntry = {
  filePath: string;
  content: string;
  /** What the user (or install) should do to activate it. */
  activateHint: string;
  deactivateHint: string;
};

/** Build the platform autostart entry. Pure — no filesystem writes. */
export function buildAutostartEntry(opts: {
  platform: NodeJS.Platform;
  env?: NodeJS.ProcessEnv;
  nodePath: string;
  cliPath: string;
  logPath: string;
}): AutostartEntry {
  const { nodePath, cliPath, logPath } = opts;
  const paths = autostartPaths(opts.platform, opts.env ?? process.env);
  switch (opts.platform) {
    case "win32": {
      const content = [
        "@echo off",
        `rem MiQroKey context agent (auto-generated by miqro-context install)`,
        `start "" /b "${nodePath}" "${cliPath}" run >> "${logPath}" 2>&1`,
        "",
      ].join("\r\n");
      return {
        filePath: paths.filePath,
        content,
        activateHint: "Windows 会在下次登录时自动运行（无需额外操作）。",
        deactivateHint: `删除文件即可：${paths.filePath}`,
      };
    }
    case "darwin":
      return {
        filePath: paths.filePath,
        content: `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>com.miqro.context</string>
    <key>ProgramArguments</key>
    <array>
        <string>${nodePath}</string>
        <string>${cliPath}</string>
        <string>run</string>
    </array>
    <key>RunAtLoad</key><true/>
    <key>StandardOutPath</key><string>${logPath}</string>
    <key>StandardErrorPath</key><string>${logPath}</string>
</dict>
</plist>
`,
        activateHint: `运行：launchctl load ${paths.filePath}`,
        deactivateHint: `运行：launchctl unload ${paths.filePath} && rm ${paths.filePath}`,
      };
    default:
      return {
        filePath: paths.filePath,
        content: `[Unit]
Description=MiQroKey context attribution agent

[Service]
ExecStart=${nodePath} ${cliPath} run
Restart=on-failure
StandardOutput=append:${logPath}
StandardError=append:${logPath}

[Install]
WantedBy=default.target
`,
        activateHint: "运行：systemctl --user daemon-reload && systemctl --user enable --now miqro-context",
        deactivateHint: "运行：systemctl --user disable --now miqro-context && rm " + paths.filePath,
      };
  }
}

/** Write the entry (idempotent). Returns the entry + file path. */
export function enableAutostart(entry: AutostartEntry): AutostartEntry {
  fs.mkdirSync(path.dirname(entry.filePath), { recursive: true });
  fs.writeFileSync(entry.filePath, entry.content);
  return entry;
}

/** Remove the entry. Silent success when absent. */
export function disableAutostart(platform: NodeJS.Platform, env: NodeJS.ProcessEnv = process.env): boolean {
  const paths = autostartPaths(platform, env);
  try {
    fs.rmSync(paths.filePath);
    return true;
  } catch {
    return false;
  }
}

export function autostartInstalled(platform: NodeJS.Platform, env: NodeJS.ProcessEnv = process.env): boolean {
  return fs.existsSync(autostartPaths(platform, env).filePath);
}
