package com.miqroera.miqrokey.controlplane.controller;

import io.swagger.v3.oas.annotations.Hidden;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;

/**
 * Test-only admin endpoints for authorization integration testing. This
 * controller is only available in the test classpath; not compiled into the
 * production artifact.
 *
 * <p>
 * Ownership/IDOR tests are in {@link OwnershipTestController} which lives
 * outside {@code /api/v1/admin/**} so USER self-access can reach
 * {@code OwnershipService} without being blocked by {@code RoleInterceptor}.
 * </p>
 *
 * <p>
 * {@link Hidden} is required, not cosmetic: the committed OpenAPI baseline is
 * generated by {@code OpenApiSpecIntegrationTest} on the test classpath, so
 * without it these endpoints are published in
 * {@code docs/openapi/openapi-3.1.json} (and from there into
 * {@code frontend/src/types/generated.ts}) even though no production deployment
 * serves them. Guarded by {@code OpenApiBaselineTestControllerLeakTest}.
 * </p>
 */
@Hidden
@RestController
@RequestMapping("/api/v1/admin")
public class AdminTestController {

    @GetMapping("/test")
    public ResponseEntity<Map<String, String>> adminTest() {
        return ResponseEntity.ok(Map.of("message", "admin access granted"));
    }

    @GetMapping("/users/{userId}")
    public ResponseEntity<Map<String, String>> adminUserDetail(@PathVariable String userId) {
        return ResponseEntity.ok(Map.of("userId", userId, "message", "user detail"));
    }
}
