-- ============================================================================
-- V1: Core tables for tenant, organization, provider catalog, credentials,
--     grants, virtual keys, and audit.
--
-- Conventions:
--   - UUIDs generated by application, stored as PostgreSQL uuid.
--   - Timestamps use timestamptz (UTC).
--   - Monetary values use numeric(24,10).
--   - Enum-like fields use varchar with CHECK constraints (not PostgreSQL enums).
--   - All mutable aggregate roots include a version bigint for optimistic locking.
--   - All tenant-scoped tables include tenant_id uuid not null.
--   - Secret ciphertext, nonce, and digests stored as bytea.
-- ============================================================================

-- ============================================================================
-- 1. Tenants
-- ============================================================================
CREATE TABLE tenants (
    id          uuid        PRIMARY KEY,
    code        varchar(64) NOT NULL,
    name        varchar(200) NOT NULL,
    status      varchar(32) NOT NULL DEFAULT 'ACTIVE'
                CHECK (status IN ('ACTIVE', 'DISABLED')),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_tenants_code ON tenants (code);

-- ============================================================================
-- 2. Users
-- ============================================================================
CREATE TABLE users (
    id                  uuid         PRIMARY KEY,
    tenant_id           uuid         NOT NULL REFERENCES tenants (id),
    username            varchar(128) NOT NULL,
    display_name        varchar(200) NOT NULL,
    password_hash       bytea        NOT NULL,
    role                varchar(32)  NOT NULL DEFAULT 'USER'
                        CHECK (role IN ('SYSTEM_ADMIN', 'USER')),
    status              varchar(32)  NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED')),
    must_change_password boolean     NOT NULL DEFAULT TRUE,
    failed_login_count  integer      NOT NULL DEFAULT 0,
    locked_until        timestamptz,
    last_login_at       timestamptz,
    version             bigint       NOT NULL DEFAULT 0,
    created_at          timestamptz  NOT NULL DEFAULT now(),
    updated_at          timestamptz  NOT NULL DEFAULT now()
);

-- Username uniqueness per tenant (case-insensitive)
CREATE UNIQUE INDEX uq_users_tenant_username
    ON users (tenant_id, lower(username));

CREATE INDEX idx_users_tenant_id ON users (tenant_id);
CREATE INDEX idx_users_status ON users (tenant_id, status);

-- ============================================================================
-- 3. Teams and Team Memberships
-- ============================================================================
CREATE TABLE teams (
    id          uuid         PRIMARY KEY,
    tenant_id   uuid         NOT NULL REFERENCES tenants (id),
    name        varchar(200) NOT NULL,
    description text,
    status      varchar(32)  NOT NULL DEFAULT 'ACTIVE'
                CHECK (status IN ('ACTIVE', 'DISABLED')),
    version     bigint       NOT NULL DEFAULT 0,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_teams_tenant_id ON teams (tenant_id);

CREATE TABLE team_memberships (
    team_id     uuid        NOT NULL REFERENCES teams (id),
    user_id     uuid        NOT NULL REFERENCES users (id),
    created_by  uuid,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (team_id, user_id)
);

CREATE INDEX idx_team_memberships_user_id ON team_memberships (user_id);

-- ============================================================================
-- 4. Projects and Project Memberships
-- ============================================================================
CREATE TABLE projects (
    id          uuid         PRIMARY KEY,
    tenant_id   uuid         NOT NULL REFERENCES tenants (id),
    code        varchar(64)  NOT NULL,
    name        varchar(200) NOT NULL,
    description text,
    cost_center varchar(64),
    status      varchar(32)  NOT NULL DEFAULT 'ACTIVE'
                CHECK (status IN ('ACTIVE', 'DISABLED')),
    version     bigint       NOT NULL DEFAULT 0,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_projects_tenant_code ON projects (tenant_id, code);
CREATE INDEX idx_projects_tenant_id ON projects (tenant_id);

CREATE TABLE project_memberships (
    project_id  uuid        NOT NULL REFERENCES projects (id),
    user_id     uuid        NOT NULL REFERENCES users (id),
    created_by  uuid,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, user_id)
);

CREATE INDEX idx_project_memberships_user_id ON project_memberships (user_id);

-- ============================================================================
-- 5. Providers
-- ============================================================================
CREATE TABLE providers (
    id                 uuid          PRIMARY KEY,
    slug               varchar(64)   NOT NULL,
    display_name       varchar(200)  NOT NULL,
    official_site_url  text,
    documentation_url  text,
    catalog_version    varchar(32),
    status             varchar(32)   NOT NULL DEFAULT 'ACTIVE'
                       CHECK (status IN ('ACTIVE', 'DISABLED')),
    version            bigint        NOT NULL DEFAULT 0,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    updated_at         timestamptz   NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_providers_slug ON providers (slug);

-- ============================================================================
-- 6. Provider Products
-- ============================================================================
CREATE TABLE provider_products (
    id                       uuid          PRIMARY KEY,
    provider_id              uuid          NOT NULL REFERENCES providers (id),
    product_code             varchar(64)   NOT NULL,
    display_name             varchar(200)  NOT NULL,
    billing_mode             varchar(32)   NOT NULL
                             CHECK (billing_mode IN (
                                 'PAYG', 'FIXED_SUBSCRIPTION',
                                 'TOKEN_PACKAGE', 'CREDIT_POOL', 'HYBRID')),
    plan_scope               varchar(32)
                             CHECK (plan_scope IS NULL OR plan_scope IN (
                                 'NONE', 'PERSONAL', 'TEAM', 'ENTERPRISE')),
    credential_topology      varchar(32)   NOT NULL
                             CHECK (credential_topology IN (
                                 'SINGLE_SHARED', 'MULTI_KEY_SHARED_POOL',
                                 'PER_SEAT_KEY', 'PER_MEMBER_SUBSCRIPTION_KEY')),
    quota_topology           varchar(32)
                             CHECK (quota_topology IS NULL OR quota_topology IN (
                                 'NONE', 'GLOBAL_SHARED', 'MEMBER_ISOLATED',
                                 'DEDICATED_PLUS_SHARED', 'KEY_CAPPED')),
    supported_wire_protocols jsonb         NOT NULL DEFAULT '[]',
    base_url_templates       jsonb         NOT NULL DEFAULT '[]',
    auth_scheme              jsonb         NOT NULL DEFAULT '{}',
    model_catalog_strategy   varchar(32),
    plan_status_strategy     varchar(32),
    balance_authority        varchar(32)
                             CHECK (balance_authority IS NULL OR balance_authority IN (
                                 'OFFICIAL_API', 'LOCAL_ESTIMATE', 'UNAVAILABLE')),
    implementation_status    varchar(32)   NOT NULL DEFAULT 'DRAFT'
                             CHECK (implementation_status IN (
                                 'DRAFT', 'DOCUMENTED', 'IMPLEMENTED',
                                 'VERIFIED', 'DEGRADED', 'DISABLED')),
    catalog_version          varchar(32),
    version                  bigint        NOT NULL DEFAULT 0,
    created_at               timestamptz   NOT NULL DEFAULT now(),
    updated_at               timestamptz   NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_provider_products_provider_code
    ON provider_products (provider_id, product_code);
CREATE INDEX idx_provider_products_provider_id ON provider_products (provider_id);

-- ============================================================================
-- 7. Upstream Subscriptions
-- ============================================================================
CREATE TABLE upstream_subscriptions (
    id                  uuid          PRIMARY KEY,
    provider_product_id uuid          NOT NULL REFERENCES provider_products (id),
    name                varchar(200)  NOT NULL,
    external_account_ref varchar(256),
    billing_mode        varchar(32)   NOT NULL
                        CHECK (billing_mode IN (
                            'PAYG', 'FIXED_SUBSCRIPTION',
                            'TOKEN_PACKAGE', 'CREDIT_POOL', 'HYBRID')),
    plan_scope          varchar(32)
                        CHECK (plan_scope IS NULL OR plan_scope IN (
                            'NONE', 'PERSONAL', 'TEAM', 'ENTERPRISE')),
    subscription_price  numeric(24,10),
    currency            varchar(3),
    period_start        timestamptz,
    period_end          timestamptz,
    renewal_at          timestamptz,
    quota_total         bigint,
    quota_unit          varchar(64),
    status              varchar(32)   NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED', 'SUSPENDED')),
    last_status_sync_at timestamptz,
    status_source       varchar(32)
                        CHECK (status_source IS NULL OR status_source IN (
                            'OFFICIAL_API', 'LOCAL_ESTIMATE', 'MANUAL_UNKNOWN')),
    version             bigint        NOT NULL DEFAULT 0,
    created_at          timestamptz   NOT NULL DEFAULT now(),
    updated_at          timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX idx_upstream_subs_product_id ON upstream_subscriptions (provider_product_id);
CREATE INDEX idx_upstream_subs_status ON upstream_subscriptions (status);

-- ============================================================================
-- 8. Plan Seats
-- ============================================================================
CREATE TABLE plan_seats (
    id                      uuid         PRIMARY KEY,
    upstream_subscription_id uuid        NOT NULL REFERENCES upstream_subscriptions (id),
    external_seat_ref       varchar(256),
    assigned_user_id        uuid         REFERENCES users (id),
    display_name            varchar(200),
    seat_status             varchar(32)  NOT NULL DEFAULT 'AVAILABLE'
                            CHECK (seat_status IN (
                                'AVAILABLE', 'ASSIGNED', 'DISABLED', 'RELEASED')),
    quota_total             bigint,
    quota_used              bigint,
    period_start            timestamptz,
    period_end              timestamptz,
    version                 bigint       NOT NULL DEFAULT 0,
    created_at              timestamptz  NOT NULL DEFAULT now(),
    updated_at              timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_plan_seats_subscription_ext_ref
    ON plan_seats (upstream_subscription_id, external_seat_ref)
    WHERE external_seat_ref IS NOT NULL;

CREATE INDEX idx_plan_seats_subscription_id ON plan_seats (upstream_subscription_id);
CREATE INDEX idx_plan_seats_user_id ON plan_seats (assigned_user_id);

-- ============================================================================
-- 9. Upstream Credentials (logical slot, no plaintext secret)
-- ============================================================================
CREATE TABLE upstream_credentials (
    id                  uuid         PRIMARY KEY,
    subscription_id     uuid         NOT NULL REFERENCES upstream_subscriptions (id),
    seat_id             uuid         REFERENCES plan_seats (id),
    credential_name     varchar(200) NOT NULL,
    secret_fingerprint  bytea,
    status              varchar(32)  NOT NULL DEFAULT 'PENDING_VALIDATION'
                        CHECK (status IN (
                            'PENDING_VALIDATION', 'ACTIVE',
                            'DRAINING', 'DISABLED', 'INVALID')),
    active_version_id   uuid,
    last_validated_at   timestamptz,
    last_validation_error text,
    version             bigint       NOT NULL DEFAULT 0,
    created_at          timestamptz  NOT NULL DEFAULT now(),
    updated_at          timestamptz  NOT NULL DEFAULT now()
);

-- NOTE: No encrypted_secret, nonce, or plaintext column exists on this table.
-- Actual secret material is stored ONLY in upstream_credential_versions.
CREATE INDEX idx_upstream_creds_subscription_id ON upstream_credentials (subscription_id);
CREATE INDEX idx_upstream_creds_seat_id ON upstream_credentials (seat_id);
CREATE INDEX idx_upstream_creds_status ON upstream_credentials (status);

-- ============================================================================
-- 10. Upstream Credential Versions (immutable, contains encrypted secret)
-- ============================================================================
CREATE TABLE upstream_credential_versions (
    id                      uuid         PRIMARY KEY,
    credential_id           uuid         NOT NULL REFERENCES upstream_credentials (id),
    encrypted_secret        bytea        NOT NULL,
    nonce                   bytea        NOT NULL,
    encryption_key_version  varchar(64)  NOT NULL,
    secret_fingerprint      bytea        NOT NULL,
    status                  varchar(32)  NOT NULL DEFAULT 'PENDING_VALIDATION'
                            CHECK (status IN (
                                'PENDING_VALIDATION', 'ACTIVE',
                                'DRAINING', 'RETIRED', 'INVALID')),
    valid_from              timestamptz,
    retired_at              timestamptz,
    created_at              timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_credential_versions_credential_id
    ON upstream_credential_versions (credential_id);

-- At most one ACTIVE version per credential
CREATE UNIQUE INDEX uq_credential_versions_one_active
    ON upstream_credential_versions (credential_id, status)
    WHERE status = 'ACTIVE';

-- ============================================================================
-- 11. Project Provider Grants
-- ============================================================================
CREATE TABLE project_provider_grants (
    id                      uuid         PRIMARY KEY,
    project_id              uuid         NOT NULL REFERENCES projects (id),
    provider_product_id     uuid         NOT NULL REFERENCES provider_products (id),
    upstream_credential_id  uuid         NOT NULL REFERENCES upstream_credentials (id),
    status                  varchar(32)  NOT NULL DEFAULT 'ACTIVE'
                            CHECK (status IN ('ACTIVE', 'DISABLED', 'EXPIRED')),
    created_by              uuid         NOT NULL,
    version                 bigint       NOT NULL DEFAULT 0,
    created_at              timestamptz  NOT NULL DEFAULT now(),
    updated_at              timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_grants_project_product_credential
    ON project_provider_grants (project_id, provider_product_id, upstream_credential_id);

CREATE INDEX idx_grants_project_id ON project_provider_grants (project_id);
CREATE INDEX idx_grants_product_id ON project_provider_grants (provider_product_id);
CREATE INDEX idx_grants_credential_id ON project_provider_grants (upstream_credential_id);
CREATE INDEX idx_grants_status ON project_provider_grants (status);

-- ============================================================================
-- 12. Project Provider Grant Models (exact, case-sensitive model IDs)
-- ============================================================================
CREATE TABLE project_provider_grant_models (
    grant_id    uuid         NOT NULL REFERENCES project_provider_grants (id),
    model_id    varchar(128) NOT NULL,
    PRIMARY KEY (grant_id, model_id)
);

-- ============================================================================
-- 13. Virtual Keys
--
-- NOTE: No plaintext key column. Only public_key_id (for lookup) and
-- secret_digest (HMAC-SHA-256 of the secret portion) are stored.
-- The full key is displayed exactly once at creation time.
-- ============================================================================
CREATE TABLE virtual_keys (
    id                      uuid         PRIMARY KEY,
    public_key_id           varchar(64)  NOT NULL,
    secret_digest           bytea        NOT NULL,
    display_prefix          varchar(16)  NOT NULL,
    last_four               varchar(4)   NOT NULL,
    user_id                 uuid         NOT NULL REFERENCES users (id),
    project_id              uuid         NOT NULL REFERENCES projects (id),
    grant_id                uuid         NOT NULL REFERENCES project_provider_grants (id),
    upstream_credential_id  uuid         NOT NULL REFERENCES upstream_credentials (id),
    purpose                 varchar(32)  NOT NULL
                            CHECK (purpose IN (
                                'CLAUDE_CODE', 'CLAUDE_DESKTOP',
                                'CODEX', 'CUSTOM')),
    name                    varchar(200),
    status                  varchar(32)  NOT NULL DEFAULT 'ACTIVE'
                            CHECK (status IN (
                                'ACTIVE', 'ROTATING', 'REVOKED', 'DISABLED')),
    created_at              timestamptz  NOT NULL DEFAULT now(),
    last_used_at            timestamptz,
    revoked_at              timestamptz,
    replaced_by_key_id      uuid,
    version                 bigint       NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX uq_virtual_keys_public_key_id ON virtual_keys (public_key_id);
CREATE INDEX idx_virtual_keys_user_id ON virtual_keys (user_id);
CREATE INDEX idx_virtual_keys_project_id ON virtual_keys (project_id);
CREATE INDEX idx_virtual_keys_grant_id ON virtual_keys (grant_id);
CREATE INDEX idx_virtual_keys_credential_id ON virtual_keys (upstream_credential_id);
CREATE INDEX idx_virtual_keys_status ON virtual_keys (status);

-- ============================================================================
-- 14. Virtual Key Models (authorization snapshot at key creation time)
-- ============================================================================
CREATE TABLE virtual_key_models (
    virtual_key_id  uuid         NOT NULL REFERENCES virtual_keys (id),
    model_id        varchar(128) NOT NULL,
    PRIMARY KEY (virtual_key_id, model_id)
);

-- ============================================================================
-- 15. Admin Audit Events (append-only, permanent, no FK cascade)
-- ============================================================================
CREATE TABLE admin_audit_events (
    id                  uuid         PRIMARY KEY,
    actor_id            uuid,
    action              varchar(64)  NOT NULL,
    target_type         varchar(64),
    target_id           uuid,
    change_summary      jsonb,
    gateway_request_id  varchar(64),
    admin_request_id    varchar(64),
    previous_event_hash bytea,
    current_event_hash  bytea        NOT NULL,
    created_at          timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_events_actor_id ON admin_audit_events (actor_id);
CREATE INDEX idx_audit_events_target ON admin_audit_events (target_type, target_id);
CREATE INDEX idx_audit_events_action ON admin_audit_events (action);
CREATE INDEX idx_audit_events_created_at ON admin_audit_events (created_at DESC);
