-- ============================================================================
-- V1: Core tables for tenant, organization, provider catalog, credentials,
--     grants, virtual keys, and audit.
--
-- Conventions:
--   - UUIDs generated by application, stored as PostgreSQL uuid.
--   - Timestamps use timestamptz (UTC).
--   - Monetary values use numeric(24,10).
--   - Enum-like fields use varchar with CHECK constraints (not PostgreSQL enums).
--   - All mutable aggregate roots include a version bigint for optimistic locking.
--   - ALL tenant-scoped tables include tenant_id uuid NOT NULL.
--   - Secret ciphertext, nonce, and digests stored as bytea.
--   - Foreign keys default to ON DELETE RESTRICT (no silent cascade).
-- ============================================================================

-- ============================================================================
-- 1. Tenants
-- ============================================================================
CREATE TABLE tenants (
    id          uuid        PRIMARY KEY,
    code        varchar(64) NOT NULL,
    name        varchar(200) NOT NULL,
    status      varchar(32) NOT NULL DEFAULT 'ACTIVE'
                CHECK (status IN ('ACTIVE', 'DISABLED')),
    version     bigint      NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_tenants_code ON tenants (code);

-- Seed the default tenant so foreign key constraints always have a valid target.
-- The UUID is deterministic and documented for first-version single-tenant use.
INSERT INTO tenants (id, code, name, status, version, created_at, updated_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'default', 'Default Tenant', 'ACTIVE', 0, now(), now());

-- ============================================================================
-- 2. Users
-- ============================================================================
CREATE TABLE users (
    id                  uuid         PRIMARY KEY,
    tenant_id           uuid         NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    username            varchar(128) NOT NULL,
    display_name        varchar(200) NOT NULL,
    password_hash       bytea        NOT NULL,
    role                varchar(32)  NOT NULL DEFAULT 'USER'
                        CHECK (role IN ('SYSTEM_ADMIN', 'USER')),
    status              varchar(32)  NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'DISABLED', 'LOCKED')),
    must_change_password boolean     NOT NULL DEFAULT TRUE,
    failed_login_count  integer      NOT NULL DEFAULT 0,
    locked_until        timestamptz,
    last_login_at       timestamptz,
    version             bigint       NOT NULL DEFAULT 0,
    created_at          timestamptz  NOT NULL DEFAULT now(),
    updated_at          timestamptz  NOT NULL DEFAULT now()
);

-- Username uniqueness per tenant (case-insensitive)
CREATE UNIQUE INDEX uq_users_tenant_username
    ON users (tenant_id, lower(username));

CREATE INDEX idx_users_tenant_id ON users (tenant_id);
CREATE INDEX idx_users_status ON users (tenant_id, status);

-- Composite unique for cross-tenant FK references
ALTER TABLE users ADD CONSTRAINT uq_users_tenant_id UNIQUE (tenant_id, id);

-- ============================================================================
-- 3. Teams and Team Memberships
-- ============================================================================
CREATE TABLE teams (
    id          uuid         PRIMARY KEY,
    tenant_id   uuid         NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    name        varchar(200) NOT NULL,
    description text,
    status      varchar(32)  NOT NULL DEFAULT 'ACTIVE'
                CHECK (status IN ('ACTIVE', 'DISABLED')),
    version     bigint       NOT NULL DEFAULT 0,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_teams_tenant_id ON teams (tenant_id);
ALTER TABLE teams ADD CONSTRAINT uq_teams_tenant_id UNIQUE (tenant_id, id);

CREATE TABLE team_memberships (
    tenant_id   uuid        NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    team_id     uuid        NOT NULL,
    user_id     uuid        NOT NULL,
    created_by  uuid,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (team_id, user_id),
    CONSTRAINT fk_team_memberships_team
        FOREIGN KEY (tenant_id, team_id) REFERENCES teams (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_team_memberships_user
        FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_team_memberships_user_id ON team_memberships (user_id);
CREATE INDEX idx_team_memberships_tenant ON team_memberships (tenant_id);

-- ============================================================================
-- 4. Projects and Project Memberships
-- ============================================================================
CREATE TABLE projects (
    id          uuid         PRIMARY KEY,
    tenant_id   uuid         NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    code        varchar(64)  NOT NULL,
    name        varchar(200) NOT NULL,
    description text,
    cost_center varchar(64),
    status      varchar(32)  NOT NULL DEFAULT 'ACTIVE'
                CHECK (status IN ('ACTIVE', 'DISABLED')),
    version     bigint       NOT NULL DEFAULT 0,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_projects_tenant_code ON projects (tenant_id, code);
CREATE INDEX idx_projects_tenant_id ON projects (tenant_id);
ALTER TABLE projects ADD CONSTRAINT uq_projects_tenant_id UNIQUE (tenant_id, id);

CREATE TABLE project_memberships (
    tenant_id   uuid        NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    project_id  uuid        NOT NULL,
    user_id     uuid        NOT NULL,
    created_by  uuid,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, user_id),
    CONSTRAINT fk_project_memberships_project
        FOREIGN KEY (tenant_id, project_id) REFERENCES projects (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_memberships_user
        FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_project_memberships_user_id ON project_memberships (user_id);
CREATE INDEX idx_project_memberships_tenant ON project_memberships (tenant_id);

-- ============================================================================
-- 5. Providers (global — non-tenant-scoped catalog reference)
-- ============================================================================
CREATE TABLE providers (
    id                 uuid          PRIMARY KEY,
    slug               varchar(64)   NOT NULL,
    display_name       varchar(200)  NOT NULL,
    official_site_url  text,
    documentation_url  text,
    catalog_version    varchar(32),
    status             varchar(32)   NOT NULL DEFAULT 'ACTIVE'
                       CHECK (status IN ('ACTIVE', 'DISABLED')),
    version            bigint        NOT NULL DEFAULT 0,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    updated_at         timestamptz   NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_providers_slug ON providers (slug);

-- ============================================================================
-- 6. Provider Products (global catalog — not tenant-scoped)
-- ============================================================================
CREATE TABLE provider_products (
    id                       uuid          PRIMARY KEY,
    provider_id              uuid          NOT NULL REFERENCES providers (id) ON DELETE RESTRICT,
    product_code             varchar(64)   NOT NULL,
    display_name             varchar(200)  NOT NULL,
    billing_mode             varchar(32)   NOT NULL
                             CHECK (billing_mode IN (
                                 'PAYG', 'FIXED_SUBSCRIPTION',
                                 'TOKEN_PACKAGE', 'CREDIT_POOL', 'HYBRID')),
    plan_scope               varchar(32)
                             CHECK (plan_scope IS NULL OR plan_scope IN (
                                 'NONE', 'PERSONAL', 'TEAM', 'ENTERPRISE')),
    credential_topology      varchar(32)   NOT NULL
                             CHECK (credential_topology IN (
                                 'SINGLE_SHARED', 'MULTI_KEY_SHARED_POOL',
                                 'PER_SEAT_KEY', 'PER_MEMBER_SUBSCRIPTION_KEY')),
    quota_topology           varchar(32)
                             CHECK (quota_topology IS NULL OR quota_topology IN (
                                 'NONE', 'GLOBAL_SHARED', 'MEMBER_ISOLATED',
                                 'DEDICATED_PLUS_SHARED', 'KEY_CAPPED')),
    supported_wire_protocols jsonb         NOT NULL DEFAULT '[]',
    base_url_templates       jsonb         NOT NULL DEFAULT '[]',
    auth_scheme              jsonb         NOT NULL DEFAULT '{}',
    model_catalog_strategy   varchar(32),
    plan_status_strategy     varchar(32),
    balance_authority        varchar(32)
                             CHECK (balance_authority IS NULL OR balance_authority IN (
                                 'OFFICIAL_API', 'LOCAL_ESTIMATE', 'UNAVAILABLE')),
    implementation_status    varchar(32)   NOT NULL DEFAULT 'DRAFT'
                             CHECK (implementation_status IN (
                                 'DRAFT', 'DOCUMENTED', 'IMPLEMENTED',
                                 'VERIFIED', 'DEGRADED', 'DISABLED')),
    catalog_version          varchar(32),
    version                  bigint        NOT NULL DEFAULT 0,
    created_at               timestamptz   NOT NULL DEFAULT now(),
    updated_at               timestamptz   NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_provider_products_provider_code
    ON provider_products (provider_id, product_code);
CREATE INDEX idx_provider_products_provider_id ON provider_products (provider_id);

-- ============================================================================
-- 7. Upstream Subscriptions (tenant-scoped)
-- ============================================================================
CREATE TABLE upstream_subscriptions (
    id                  uuid          PRIMARY KEY,
    tenant_id           uuid          NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    provider_product_id uuid          NOT NULL REFERENCES provider_products (id) ON DELETE RESTRICT,
    name                varchar(200)  NOT NULL,
    external_account_ref varchar(256),
    billing_mode        varchar(32)   NOT NULL
                        CHECK (billing_mode IN (
                            'PAYG', 'FIXED_SUBSCRIPTION',
                            'TOKEN_PACKAGE', 'CREDIT_POOL', 'HYBRID')),
    plan_scope          varchar(32)
                        CHECK (plan_scope IS NULL OR plan_scope IN (
                            'NONE', 'PERSONAL', 'TEAM', 'ENTERPRISE')),
    subscription_price  numeric(24,10),
    currency            varchar(3),
    period_start        timestamptz,
    period_end          timestamptz,
    renewal_at          timestamptz,
    quota_total         bigint,
    quota_unit          varchar(64),
    status              varchar(32)   NOT NULL DEFAULT 'ACTIVE'
                        CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED', 'SUSPENDED')),
    last_status_sync_at timestamptz,
    status_source       varchar(32)
                        CHECK (status_source IS NULL OR status_source IN (
                            'OFFICIAL_API', 'LOCAL_ESTIMATE', 'MANUAL_UNKNOWN')),
    version             bigint        NOT NULL DEFAULT 0,
    created_at          timestamptz   NOT NULL DEFAULT now(),
    updated_at          timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX idx_upstream_subs_product_id ON upstream_subscriptions (provider_product_id);
CREATE INDEX idx_upstream_subs_status ON upstream_subscriptions (status);
CREATE INDEX idx_upstream_subs_tenant_id ON upstream_subscriptions (tenant_id);
ALTER TABLE upstream_subscriptions ADD CONSTRAINT uq_upstream_subs_tenant_id UNIQUE (tenant_id, id);

-- ============================================================================
-- 8. Plan Seats (tenant-scoped)
-- ============================================================================
CREATE TABLE plan_seats (
    id                      uuid         PRIMARY KEY,
    tenant_id               uuid         NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    upstream_subscription_id uuid        NOT NULL,
    external_seat_ref       varchar(256),
    assigned_user_id        uuid,
    display_name            varchar(200),
    seat_status             varchar(32)  NOT NULL DEFAULT 'AVAILABLE'
                            CHECK (seat_status IN (
                                'AVAILABLE', 'ASSIGNED', 'DISABLED', 'RELEASED')),
    quota_total             bigint,
    quota_used              bigint,
    period_start            timestamptz,
    period_end              timestamptz,
    version                 bigint       NOT NULL DEFAULT 0,
    created_at              timestamptz  NOT NULL DEFAULT now(),
    updated_at              timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_plan_seats_subscription
        FOREIGN KEY (tenant_id, upstream_subscription_id)
        REFERENCES upstream_subscriptions (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_plan_seats_user
        FOREIGN KEY (assigned_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_plan_seats_subscription_ext_ref
    ON plan_seats (upstream_subscription_id, external_seat_ref)
    WHERE external_seat_ref IS NOT NULL;

CREATE INDEX idx_plan_seats_subscription_id ON plan_seats (upstream_subscription_id);
CREATE INDEX idx_plan_seats_user_id ON plan_seats (assigned_user_id);
CREATE INDEX idx_plan_seats_tenant_id ON plan_seats (tenant_id);

-- ============================================================================
-- 9. Upstream Credentials (tenant-scoped; logical slot, no plaintext secret)
-- ============================================================================
CREATE TABLE upstream_credentials (
    id                  uuid         PRIMARY KEY,
    tenant_id           uuid         NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    subscription_id     uuid         NOT NULL,
    seat_id             uuid         REFERENCES plan_seats (id) ON DELETE SET NULL,
    credential_name     varchar(200) NOT NULL,
    secret_fingerprint  bytea,
    status              varchar(32)  NOT NULL DEFAULT 'PENDING_VALIDATION'
                        CHECK (status IN (
                            'PENDING_VALIDATION', 'ACTIVE',
                            'DRAINING', 'DISABLED', 'INVALID')),
    active_version_id   uuid,
    last_validated_at   timestamptz,
    last_validation_error text,
    version             bigint       NOT NULL DEFAULT 0,
    created_at          timestamptz  NOT NULL DEFAULT now(),
    updated_at          timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_upstream_creds_subscription
        FOREIGN KEY (tenant_id, subscription_id)
        REFERENCES upstream_subscriptions (tenant_id, id) ON DELETE RESTRICT
);

-- NOTE: No encrypted_secret, nonce, or plaintext column exists on this table.
-- Actual secret material is stored ONLY in upstream_credential_versions.
CREATE INDEX idx_upstream_creds_subscription_id ON upstream_credentials (subscription_id);
CREATE INDEX idx_upstream_creds_seat_id ON upstream_credentials (seat_id);
CREATE INDEX idx_upstream_creds_status ON upstream_credentials (status);
CREATE INDEX idx_upstream_creds_tenant_id ON upstream_credentials (tenant_id);
ALTER TABLE upstream_credentials ADD CONSTRAINT uq_upstream_creds_tenant_id UNIQUE (tenant_id, id);

-- active_version_id FK added below after upstream_credential_versions is created

-- ============================================================================
-- 10. Upstream Credential Versions (tenant-scoped; immutable, contains encrypted secret)
-- ============================================================================
CREATE TABLE upstream_credential_versions (
    id                      uuid         PRIMARY KEY,
    tenant_id               uuid         NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    credential_id           uuid         NOT NULL,
    encrypted_secret        bytea        NOT NULL,
    nonce                   bytea        NOT NULL,
    encryption_key_version  varchar(64)  NOT NULL,
    secret_fingerprint      bytea        NOT NULL,
    status                  varchar(32)  NOT NULL DEFAULT 'PENDING_VALIDATION'
                            CHECK (status IN (
                                'PENDING_VALIDATION', 'ACTIVE',
                                'DRAINING', 'RETIRED', 'INVALID')),
    valid_from              timestamptz,
    retired_at              timestamptz,
    created_at              timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_credential_versions_credential
        FOREIGN KEY (tenant_id, credential_id)
        REFERENCES upstream_credentials (tenant_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_credential_versions_credential_id
    ON upstream_credential_versions (credential_id);
CREATE INDEX idx_credential_versions_tenant_id
    ON upstream_credential_versions (tenant_id);

-- At most one ACTIVE version per credential
CREATE UNIQUE INDEX uq_credential_versions_one_active
    ON upstream_credential_versions (credential_id, status)
    WHERE status = 'ACTIVE';

-- Now add the active_version_id FK back on upstream_credentials
ALTER TABLE upstream_credentials
    ADD CONSTRAINT fk_upstream_creds_active_version
        FOREIGN KEY (active_version_id) REFERENCES upstream_credential_versions (id) ON DELETE SET NULL;

-- ============================================================================
-- 11. Project Provider Grants (tenant-scoped)
-- ============================================================================
CREATE TABLE project_provider_grants (
    id                      uuid         PRIMARY KEY,
    tenant_id               uuid         NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    project_id              uuid         NOT NULL,
    provider_product_id     uuid         NOT NULL REFERENCES provider_products (id) ON DELETE RESTRICT,
    upstream_credential_id  uuid         NOT NULL,
    status                  varchar(32)  NOT NULL DEFAULT 'ACTIVE'
                            CHECK (status IN ('ACTIVE', 'DISABLED', 'EXPIRED')),
    created_by              uuid         NOT NULL,
    version                 bigint       NOT NULL DEFAULT 0,
    created_at              timestamptz  NOT NULL DEFAULT now(),
    updated_at              timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_grants_project
        FOREIGN KEY (tenant_id, project_id) REFERENCES projects (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_grants_credential
        FOREIGN KEY (tenant_id, upstream_credential_id)
        REFERENCES upstream_credentials (tenant_id, id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_grants_project_product_credential
    ON project_provider_grants (project_id, provider_product_id, upstream_credential_id);

CREATE INDEX idx_grants_project_id ON project_provider_grants (project_id);
CREATE INDEX idx_grants_product_id ON project_provider_grants (provider_product_id);
CREATE INDEX idx_grants_credential_id ON project_provider_grants (upstream_credential_id);
CREATE INDEX idx_grants_status ON project_provider_grants (status);
CREATE INDEX idx_grants_tenant_id ON project_provider_grants (tenant_id);
ALTER TABLE project_provider_grants ADD CONSTRAINT uq_grants_tenant_id UNIQUE (tenant_id, id);

-- ============================================================================
-- 12. Project Provider Grant Models (tenant-scoped; exact, case-sensitive model IDs)
-- ============================================================================
CREATE TABLE project_provider_grant_models (
    tenant_id   uuid         NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    grant_id    uuid         NOT NULL,
    model_id    varchar(128) NOT NULL,
    PRIMARY KEY (grant_id, model_id),
    CONSTRAINT fk_grant_models_grant
        FOREIGN KEY (tenant_id, grant_id) REFERENCES project_provider_grants (tenant_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_grant_models_tenant_id ON project_provider_grant_models (tenant_id);

-- ============================================================================
-- 13. Virtual Keys (tenant-scoped)
--
-- NOTE: No plaintext key column. Only public_key_id (for lookup) and
-- secret_digest (HMAC-SHA-256 of the secret portion) are stored.
-- The full key is displayed exactly once at creation time.
-- ============================================================================
CREATE TABLE virtual_keys (
    id                      uuid         PRIMARY KEY,
    tenant_id               uuid         NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    public_key_id           varchar(64)  NOT NULL,
    secret_digest           bytea        NOT NULL,
    display_prefix          varchar(16)  NOT NULL,
    last_four               varchar(4)   NOT NULL,
    user_id                 uuid         NOT NULL,
    project_id              uuid         NOT NULL,
    grant_id                uuid         NOT NULL,
    upstream_credential_id  uuid         NOT NULL,
    purpose                 varchar(32)  NOT NULL
                            CHECK (purpose IN (
                                'CLAUDE_CODE', 'CLAUDE_DESKTOP',
                                'CODEX', 'CUSTOM')),
    name                    varchar(200),
    status                  varchar(32)  NOT NULL DEFAULT 'ACTIVE'
                            CHECK (status IN (
                                'ACTIVE', 'ROTATING', 'REVOKED', 'DISABLED')),
    created_at              timestamptz  NOT NULL DEFAULT now(),
    last_used_at            timestamptz,
    revoked_at              timestamptz,
    replaced_by_key_id      uuid,
    version                 bigint       NOT NULL DEFAULT 0,
    CONSTRAINT fk_virtual_keys_user
        FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_virtual_keys_project
        FOREIGN KEY (tenant_id, project_id) REFERENCES projects (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_virtual_keys_grant
        FOREIGN KEY (tenant_id, grant_id) REFERENCES project_provider_grants (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_virtual_keys_credential
        FOREIGN KEY (tenant_id, upstream_credential_id)
        REFERENCES upstream_credentials (tenant_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_virtual_keys_replaced_by
        FOREIGN KEY (replaced_by_key_id) REFERENCES virtual_keys (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_virtual_keys_public_key_id ON virtual_keys (public_key_id);
CREATE INDEX idx_virtual_keys_user_id ON virtual_keys (user_id);
CREATE INDEX idx_virtual_keys_project_id ON virtual_keys (project_id);
CREATE INDEX idx_virtual_keys_grant_id ON virtual_keys (grant_id);
CREATE INDEX idx_virtual_keys_credential_id ON virtual_keys (upstream_credential_id);
CREATE INDEX idx_virtual_keys_status ON virtual_keys (status);
CREATE INDEX idx_virtual_keys_tenant_id ON virtual_keys (tenant_id);
ALTER TABLE virtual_keys ADD CONSTRAINT uq_virtual_keys_tenant_id UNIQUE (tenant_id, id);

-- ============================================================================
-- 14. Virtual Key Models (tenant-scoped; authorization snapshot at key creation time)
-- ============================================================================
CREATE TABLE virtual_key_models (
    tenant_id       uuid         NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    virtual_key_id  uuid         NOT NULL,
    model_id        varchar(128) NOT NULL,
    PRIMARY KEY (virtual_key_id, model_id),
    CONSTRAINT fk_virtual_key_models_key
        FOREIGN KEY (tenant_id, virtual_key_id) REFERENCES virtual_keys (tenant_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_virtual_key_models_tenant_id ON virtual_key_models (tenant_id);

-- ============================================================================
-- 15. Admin Audit Events (tenant-scoped; append-only, permanent, no FK cascade)
-- ============================================================================
CREATE TABLE admin_audit_events (
    id                  uuid         PRIMARY KEY,
    tenant_id           uuid         NOT NULL REFERENCES tenants (id) ON DELETE RESTRICT,
    actor_id            uuid,
    action              varchar(64)  NOT NULL,
    target_type         varchar(64),
    target_id           uuid,
    change_summary      jsonb,
    gateway_request_id  varchar(64),
    admin_request_id    varchar(64),
    previous_event_hash bytea,
    current_event_hash  bytea        NOT NULL,
    created_at          timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_events_actor_id ON admin_audit_events (actor_id);
CREATE INDEX idx_audit_events_target ON admin_audit_events (target_type, target_id);
CREATE INDEX idx_audit_events_action ON admin_audit_events (action);
CREATE INDEX idx_audit_events_created_at ON admin_audit_events (created_at DESC);
CREATE INDEX idx_audit_events_tenant_id ON admin_audit_events (tenant_id);

-- ============================================================================
-- 16. Tenant consistency triggers (reject cross-tenant relationships at DB level)
-- ============================================================================

-- virtual_keys: grant must match tenant, project, credential; credential
-- must belong to a subscription whose provider_product matches the grant
CREATE OR REPLACE FUNCTION check_virtual_key_tenant_consistency()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM project_provider_grants g
        WHERE g.tenant_id = NEW.tenant_id
          AND g.id = NEW.grant_id
          AND g.project_id = NEW.project_id
          AND g.upstream_credential_id = NEW.upstream_credential_id
    ) THEN
        RAISE EXCEPTION 'virtual_key grant_id=% does not match tenant_id=%, project_id=%, credential_id=%',
            NEW.grant_id, NEW.tenant_id, NEW.project_id, NEW.upstream_credential_id;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM upstream_credentials c
        JOIN upstream_subscriptions s
            ON s.tenant_id = c.tenant_id AND s.id = c.subscription_id
        JOIN project_provider_grants g
            ON g.tenant_id = c.tenant_id AND g.upstream_credential_id = c.id
        WHERE c.tenant_id = NEW.tenant_id
          AND c.id = NEW.upstream_credential_id
          AND g.id = NEW.grant_id
          AND s.provider_product_id = g.provider_product_id
    ) THEN
        RAISE EXCEPTION 'virtual_key credential_id=% grant_id=%: credential subscription provider_product does not match grant provider_product',
            NEW.upstream_credential_id, NEW.grant_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_virtual_key_tenant_consistency ON virtual_keys;
CREATE TRIGGER trg_virtual_key_tenant_consistency
    BEFORE INSERT OR UPDATE ON virtual_keys
    FOR EACH ROW EXECUTE FUNCTION check_virtual_key_tenant_consistency();

-- project_provider_grants: credential must belong to a subscription whose
-- provider_product matches the grant's provider_product
CREATE OR REPLACE FUNCTION check_grant_credential_product_consistency()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM upstream_credentials c
        JOIN upstream_subscriptions s
            ON s.tenant_id = c.tenant_id AND s.id = c.subscription_id
        WHERE c.tenant_id = NEW.tenant_id
          AND c.id = NEW.upstream_credential_id
          AND s.provider_product_id = NEW.provider_product_id
    ) THEN
        RAISE EXCEPTION 'grant credential_id=%: its subscription provider_product_id does not match grant provider_product_id=%',
            NEW.upstream_credential_id, NEW.provider_product_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_grant_credential_product_consistency ON project_provider_grants;
CREATE TRIGGER trg_grant_credential_product_consistency
    BEFORE INSERT OR UPDATE ON project_provider_grants
    FOR EACH ROW EXECUTE FUNCTION check_grant_credential_product_consistency();
