-- ============================================================================
-- 60. request_usage_records: index for single-call lookup (#705).
--
--     The model-call timeline resolves one call by
--     (tenant_id, gateway_request_id) — the same triple the writer uses as its
--     idempotency key. Without a matching index the planner falls back to a
--     sequential scan of every partition (verified by EXPLAIN on the demo
--     instance: "Seq Scan on request_usage_records_default"), because the
--     existing indexes lead with tenant/project/key/product/status and the
--     primary key is (started_at, id).
--
--     Why it matters even though it measures fine today: at ~4.6k rows the
--     scan costs 0.03 ms, so nothing looks wrong — the cost only becomes
--     visible once the table grows, and the timeline is exactly the page
--     people open when something is already slow.
--
--     Note on locking: a plain CREATE INDEX takes a SHARE lock that blocks
--     writes for the duration. That is acceptable here (the table is small in
--     every environment we run today, and Flyway runs this in a transaction so
--     CONCURRENTLY is not available). If this ever needs to run against a
--     large production table, add the index out-of-band with CONCURRENTLY
--     first and mark this migration as already applied.
--
--     The index is declared on the partitioned parent, so it is created on
--     every existing partition and inherited by future ones.
-- ============================================================================
CREATE INDEX idx_request_usage_records_gateway_request
    ON request_usage_records (tenant_id, gateway_request_id);
